global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'php-service'
    static_configs:
      - targets: ['host.docker.internal:8080']
