version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  producer_1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BEARER_TOKEN=AAAAAAAAAAAAAAAAAAAAAFsk3QEAAAAAA%2BHotdC0qlY%2BXDQaM9sPSwXZYJ8%3DRWWnAVPj2yMRumJOnxd4oUd0D0ezenxuFgnkW4d6dh5XVTwNyD
      - SEARCH_QUERIES=#btc,#bitcoin,#bullish,#crypto
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - INITIAL_DELAY=0
    command: ["sh", "-c", "python wait_for_kafka.py && python producer.py"]
  producer_2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BEARER_TOKEN=AAAAAAAAAAAAAAAAAAAAAPM03QEAAAAAUk%2BTC%2FD8Kq7jxWNSiUo3ZEAW9pU%3D2dWJ58CpGZQ2AWYblTmvOdSgLUDfVnrdkDZKS0M8YC3Ie7qKqn
      - SEARCH_QUERIES=#innovation,#tech,#electronic,#device,#gadgets
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - INITIAL_DELAY=30
    command: ["sh", "-c", "python wait_for_kafka.py && python producer.py"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elk-python
    depends_on:
      - kafka
      - elasticsearch
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ELASTICSEARCH_URL=http://elasticsearch:9200/twitter/_doc/
    command: ["python", "buscar_productos.py"]
    # Usa esta línea si quieres cambiar entre producer.py y consumer.py
    # command: ["python", "consumer.py"]
